/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HubRouteImport } from './routes/hub'
import { Route as ExportPrintRouteImport } from './routes/export-print'
import { Route as ExportRouteImport } from './routes/export'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlideNRouteImport } from './routes/slide.$n'
import { Route as ModulSlugRouteImport } from './routes/modul.$slug'
import { Route as ExportPrintRouteImport } from './routes/export.print'
import { Route as CaseSlugRouteImport } from './routes/case.$slug'

const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportPrintRoute = ExportPrintRouteImport.update({
  id: '/export-print',
  path: '/export-print',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideNRoute = SlideNRouteImport.update({
  id: '/slide/$n',
  path: '/slide/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulSlugRoute = ModulSlugRouteImport.update({
  id: '/modul/$slug',
  path: '/modul/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportPrintRoute = ExportPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => ExportRoute,
} as any)
const CaseSlugRoute = CaseSlugRouteImport.update({
  id: '/case/$slug',
  path: '/case/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/export': typeof ExportRouteWithChildren
  '/export-print': typeof ExportPrintRoute
  '/hub': typeof HubRoute
  '/case/$slug': typeof CaseSlugRoute
  '/export/print': typeof ExportPrintRoute
  '/modul/$slug': typeof ModulSlugRoute
  '/slide/$n': typeof SlideNRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/export': typeof ExportRouteWithChildren
  '/export-print': typeof ExportPrintRoute
  '/hub': typeof HubRoute
  '/case/$slug': typeof CaseSlugRoute
  '/export/print': typeof ExportPrintRoute
  '/modul/$slug': typeof ModulSlugRoute
  '/slide/$n': typeof SlideNRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/export': typeof ExportRouteWithChildren
  '/export-print': typeof ExportPrintRoute
  '/hub': typeof HubRoute
  '/case/$slug': typeof CaseSlugRoute
  '/export/print': typeof ExportPrintRoute
  '/modul/$slug': typeof ModulSlugRoute
  '/slide/$n': typeof SlideNRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/export'
    | '/export-print'
    | '/hub'
    | '/case/$slug'
    | '/export/print'
    | '/modul/$slug'
    | '/slide/$n'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/export'
    | '/export-print'
    | '/hub'
    | '/case/$slug'
    | '/export/print'
    | '/modul/$slug'
    | '/slide/$n'
  id:
    | '__root__'
    | '/'
    | '/export'
    | '/export-print'
    | '/hub'
    | '/case/$slug'
    | '/export/print'
    | '/modul/$slug'
    | '/slide/$n'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExportRoute: typeof ExportRouteWithChildren
  ExportPrintRoute: typeof ExportPrintRoute
  HubRoute: typeof HubRoute
  CaseSlugRoute: typeof CaseSlugRoute
  ModulSlugRoute: typeof ModulSlugRoute
  SlideNRoute: typeof SlideNRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-print': {
      id: '/export-print'
      path: '/export-print'
      fullPath: '/export-print'
      preLoaderRoute: typeof ExportPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide/$n': {
      id: '/slide/$n'
      path: '/slide/$n'
      fullPath: '/slide/$n'
      preLoaderRoute: typeof SlideNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modul/$slug': {
      id: '/modul/$slug'
      path: '/modul/$slug'
      fullPath: '/modul/$slug'
      preLoaderRoute: typeof ModulSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export/print': {
      id: '/export/print'
      path: '/print'
      fullPath: '/export/print'
      preLoaderRoute: typeof ExportPrintRouteImport
      parentRoute: typeof ExportRoute
    }
    '/case/$slug': {
      id: '/case/$slug'
      path: '/case/$slug'
      fullPath: '/case/$slug'
      preLoaderRoute: typeof CaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExportRouteChildren {
  ExportPrintRoute: typeof ExportPrintRoute
}

const ExportRouteChildren: ExportRouteChildren = {
  ExportPrintRoute: ExportPrintRoute,
}

const ExportRouteWithChildren =
  ExportRoute._addFileChildren(ExportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExportRoute: ExportRouteWithChildren,
  ExportPrintRoute: ExportPrintRoute,
  HubRoute: HubRoute,
  CaseSlugRoute: CaseSlugRoute,
  ModulSlugRoute: ModulSlugRoute,
  SlideNRoute: SlideNRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
