/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RapportRouteImport } from './routes/rapport'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HubRouteImport } from './routes/hub'
import { Route as ExportRouteImport } from './routes/export'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlideNRouteImport } from './routes/slide.$n'
import { Route as ModulSlugRouteImport } from './routes/modul.$slug'
import { Route as ExportPrintRouteImport } from './routes/export.print'
import { Route as CaseSlugRouteImport } from './routes/case.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const RapportRoute = RapportRouteImport.update({
  id: '/rapport',
  path: '/rapport',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideNRoute = SlideNRouteImport.update({
  id: '/slide/$n',
  path: '/slide/$n',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulSlugRoute = ModulSlugRouteImport.update({
  id: '/modul/$slug',
  path: '/modul/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportPrintRoute = ExportPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => ExportRoute,
} as any)
const CaseSlugRoute = CaseSlugRouteImport.update({
  id: '/case/$slug',
  path: '/case/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/export': typeof ExportRouteWithChildren
  '/hub': typeof HubRoute
  '/mcp': typeof McpRoute
  '/rapport': typeof RapportRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/case/$slug': typeof CaseSlugRoute
  '/export/print': typeof ExportPrintRoute
  '/modul/$slug': typeof ModulSlugRoute
  '/slide/$n': typeof SlideNRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/export': typeof ExportRouteWithChildren
  '/hub': typeof HubRoute
  '/mcp': typeof McpRoute
  '/rapport': typeof RapportRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/case/$slug': typeof CaseSlugRoute
  '/export/print': typeof ExportPrintRoute
  '/modul/$slug': typeof ModulSlugRoute
  '/slide/$n': typeof SlideNRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/export': typeof ExportRouteWithChildren
  '/hub': typeof HubRoute
  '/mcp': typeof McpRoute
  '/rapport': typeof RapportRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/case/$slug': typeof CaseSlugRoute
  '/export/print': typeof ExportPrintRoute
  '/modul/$slug': typeof ModulSlugRoute
  '/slide/$n': typeof SlideNRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/export'
    | '/hub'
    | '/mcp'
    | '/rapport'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/case/$slug'
    | '/export/print'
    | '/modul/$slug'
    | '/slide/$n'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/export'
    | '/hub'
    | '/mcp'
    | '/rapport'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/case/$slug'
    | '/export/print'
    | '/modul/$slug'
    | '/slide/$n'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/export'
    | '/hub'
    | '/mcp'
    | '/rapport'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/case/$slug'
    | '/export/print'
    | '/modul/$slug'
    | '/slide/$n'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExportRoute: typeof ExportRouteWithChildren
  HubRoute: typeof HubRoute
  McpRoute: typeof McpRoute
  RapportRoute: typeof RapportRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CaseSlugRoute: typeof CaseSlugRoute
  ModulSlugRoute: typeof ModulSlugRoute
  SlideNRoute: typeof SlideNRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rapport': {
      id: '/rapport'
      path: '/rapport'
      fullPath: '/rapport'
      preLoaderRoute: typeof RapportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slide/$n': {
      id: '/slide/$n'
      path: '/slide/$n'
      fullPath: '/slide/$n'
      preLoaderRoute: typeof SlideNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modul/$slug': {
      id: '/modul/$slug'
      path: '/modul/$slug'
      fullPath: '/modul/$slug'
      preLoaderRoute: typeof ModulSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export/print': {
      id: '/export/print'
      path: '/print'
      fullPath: '/export/print'
      preLoaderRoute: typeof ExportPrintRouteImport
      parentRoute: typeof ExportRoute
    }
    '/case/$slug': {
      id: '/case/$slug'
      path: '/case/$slug'
      fullPath: '/case/$slug'
      preLoaderRoute: typeof CaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExportRouteChildren {
  ExportPrintRoute: typeof ExportPrintRoute
}

const ExportRouteChildren: ExportRouteChildren = {
  ExportPrintRoute: ExportPrintRoute,
}

const ExportRouteWithChildren =
  ExportRoute._addFileChildren(ExportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExportRoute: ExportRouteWithChildren,
  HubRoute: HubRoute,
  McpRoute: McpRoute,
  RapportRoute: RapportRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CaseSlugRoute: CaseSlugRoute,
  ModulSlugRoute: ModulSlugRoute,
  SlideNRoute: SlideNRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
